using Arayuzler_ornek;
Console.WriteLine("*********INTERFACE**********");
Focus focus = new Focus();
Console.WriteLine(focus.HagniMarkanınAraci().ToString());
Console.WriteLine(focus.KacTekerlektenOlusur().ToString());
Console.WriteLine(focus.StandartRengiNe().ToString());
Console.WriteLine("*******************");
Civic civic = new Civic();
Console.WriteLine(civic.HagniMarkanınAraci().ToString());
Console.WriteLine(civic.KacTekerlektenOlusur().ToString());
Console.WriteLine(civic.StandartRengiNe().ToString());
Console.WriteLine("*********ABSTRACT**********");
NewFocus focus1 = new NewFocus();
Console.WriteLine(focus1.HagniMarkanınAraci().ToString());
Console.WriteLine(focus1.KacTekerlektenOlusur().ToString());
Console.WriteLine(focus1.StandartRengiNe().ToString());
Console.WriteLine("*******************");
NewCivic civic1 = new NewCivic();
Console.WriteLine(civic1.HagniMarkanınAraci().ToString());
Console.WriteLine(civic1.KacTekerlektenOlusur().ToString());
Console.WriteLine(civic1.StandartRengiNe().ToString());